name: File sync

on:
  push:
    branches: [ "master" ]
    paths: "fileToSync"
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: kbrashears5/github-action-file-sync@e2715cb544edee3eff1aae1efbca9be0136e276f
        with:
          REPOSITORIES: |
            alexkar598/filecopyrepo2@master
          FILES: |
            fileToSync=syncedFile
          TOKEN: ${{ secrets.SYNC_SECRET }}
          GIT_USERNAME: SpaceManiac/SpacemanDMM
          GIT_EMAIL: action@github.com
